# Generated by Django 6.0.2 on 2026-02-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('excerpt', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('author_id', models.CharField(max_length=100)),
                ('author_email', models.EmailField(max_length=254)),
                ('author_name', models.CharField(default='Author', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.URLField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('views_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('likes_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceItem',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('type', models.CharField(choices=[('Product', 'Product'), ('Service', 'Service'), ('Event', 'Event')], default='Product', max_length=20)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('image', models.URLField(blank=True)),
                ('owner_id', models.CharField(max_length=100)),
                ('owner_email', models.EmailField(max_length=254)),
                ('owner_name', models.CharField(default='Test User', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('author_id', models.CharField(max_length=100)),
                ('author_email', models.EmailField(max_length=254)),
                ('author_name', models.CharField(default='Author', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('likes_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
