# Generated by Django 5.2.5 on 2025-11-02 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_fix_timestamps'),
        ('articles', '0004_alter_category_options_alter_article_created_at_and_more'),
    ]

    operations = [
    ]
