# Generated by Django 5.2.7 on 2025-12-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_listing_countrycode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={},
        ),
        migrations.RemoveField(
            model_name='listing',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='countryCode',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='date',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='image',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='type',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='listing',
            name='currency',
            field=models.CharField(choices=[('KSH', 'Kenyan Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('ZAR', 'South African Rand'), ('UGX', 'Ugandan Shilling'), ('TZS', 'Tanzanian Shilling'), ('RWF', 'Rwandan Franc'), ('ETB', 'Ethiopian Birr'), ('NGN', 'Nigerian Naira'), ('GHS', 'Ghanaian Cedi')], default='KSH', max_length=10),
        ),
    ]
